### ISSUE TITLE
Uglify Problem - using browserify w/ gulp

### ISSUE THREAD

**Issue by andymans** [TehShrike/sveltify#2]
I've created a gulp/browserify build which includes an uglify step.

This works fine if I'm using an HTML component that has NO `<script></script>` block. Sveltify works fine and the output is minified and uglified as I'd expect.

However, with a `<script></script>` block added, the uglify step fails with:

 'GulpUglifyError: unable to minify JavaScript'

Any ideas what might be a solution?

**Comment by TehShrike** [comment]
What order are you applying your gulp transforms in?

I'm not intimately familiar with Uglify, but I know it's not ES6-aware.  If you output the JS as it exists right before being transformed by Uglify, is Uglify able to minify that JavaScript?

Also, if you're using Babel, you might want to take a look at [babili](https://github.com/babel/babili).

**Comment by andymans** [comment]
So the transforms are ordered:
1. browserify(babelify.configure(options))
2. sveltify
3. bundle
4. pipe to 'app.out.js' (tmp for streaming)
5. pipe( streamify( uglify() ) )
-----
It fails at 5. Clearly an ES6 issue with uglify.
I have actually solved the issue by using a svelte rollup build - which includes an uglify step, and it all works fine. I'l take a look at babeli too though.

**Comment by andymans** [comment]
Closing as I believe this is not an issue with sveltify, but with uglify.

**Comment by TehShrike** [comment]
sveltify should be used as a browserify transform (an option passed in to browserify), not a standalone step - and you'll want to make sure it's before the babelify transform, so that any ES6 code you write in your Svelte components will be properly transformed.

**Comment by andymans** [comment]
Aha. That's good info. I'll try invoking the sveltify transform first, and see if that solves it.
