### ISSUE TITLE
Support for pug templates

### ISSUE THREAD

**Issue by marcalc** [TehShrike/sveltify#4]
Hey,

Sorry to bother, but is there on the roadmap to support pug templates in the same fashion as vueify does?

Thanks,

Marcos

**Comment by TehShrike** [comment]
You probably meant to open this issue on the [sveltejs/svelte](https://github.com/sveltejs/svelte) repo - it looks like there's a related issue open there already: https://github.com/sveltejs/svelte/issues/41
