### ISSUE TITLE
Svelte 2.0 issue

### ISSUE THREAD

**Issue by Nexxtron** [TehShrike/sveltify#8]
Hello,
since Svelte Version 2.0 i get following Error:
TypeError: Cannot read property 'toUrl' of undefined while parsing file

I think thats because of removing the map/code property in following svelte commit:
https://github.com/sveltejs/svelte/commit/a3add04e7c7cd0b68ddf67c67e505a156e1d797b#diff-f41e9d04a45c83f3b6f6e630f10117fe

Any chance to fix this? 
Thanks!

**Comment by TehShrike** [comment]
I'll bet you're right.

Pull request welcome, otherwise I can probably get to this later.

**Comment by TehShrike** [comment]
Fix published as `sveltify@2.0.0`
