### ISSUE TITLE
I can't use with babelify

### ISSUE THREAD

**Issue by luizbills** [TehShrike/sveltify#9]
When I use sveltify and babelify together, some parts of the code are not transpiled by babel.

**Comment by TehShrike** [comment]
Can you link to a repo demonstrating the problem?

Make sure that the sveltify transform is applied before the babelify transform.

Also make sure that your babelify transform is being applied to files with the `.html` extension (or `.svelte` or whatever else you may use).

**Comment by luizbills** [comment]
> Also make sure that your babelify transform is being applied to files with the .html extension (or .svelte or whatever else you may use).

This part will be hard haha. But that must be what's happening. I'll build a repo to show you

**Comment by luizbills** [comment]
@TehShrike Thanks, man. Applying `.html` as extension in babelify options works.

My `package.json` for reference:

```json
  "browserify": {
    "transform": [
      [
        "sveltify"
      ],
      [
        "babelify",
        {
          "presets": [
            "@babel/preset-env"
          ],
          "extensions": [
            ".html",
            ".js"
          ]
        }
      ]
    ]
  }
```
